### ISSUE TITLE
Output hidden from 'cargo test -- --nocapture'

### ISSUE THREAD

**Issue by martinlindhe** [chrivers/rust-colog#1]
Hello and thanks for this crate. I just started with rust and found it useful.

The other day I was debugging a failing test and some google-fu taught me that "cargo test" hides text output by default, but that it can be enabled by passing the slightly arcane parameter `-- --nocapture` to the `cargo test` command.

This makes lines such as
```rust
println!("something happened");
```
show up in the test output.
But since I sprinkled error!() and such over my code from using this crate, I found out that none of the output from these macros of colog is outputted, so I had to stop using colog.

I don't know enough of rust to have a stab at figuring out the issue myself, but I hope it's doable.

An example to demonstrate,
src\lib.rs:
```rust
#[macro_use]
extern crate log;
extern crate colog;

fn do_stuff() -> bool {
    println!("println");
    error!("error");
    true
}

#[test]
fn my_test() {
    assert_eq!(true, do_stuff());
}
```

run `cargo test -- --nocapture` 

the "error" is not shown:

```
  Compiling xxx v0.1.0 (file:///home/m/dev/rs/colog-test)

    Finished dev [unoptimized + debuginfo] target(s) in 0.37 secs
     Running target/debug/deps/xxx-16443244d826d912

running 1 test
println
test my_test ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured

   Doc-tests xxx

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured
```

**Comment by martinlindhe** [comment]
Okay so this was written a bit too soon. I just realized the same is true for the "log" package, so no bug in this crate.

I found it is possible to enable logging in tests, documented here: https://github.com/rust-lang-nursery/log/pull/56/

However, it is a manual process. Sorry for the noise

**Comment by chrivers** [comment]
Hi! I meant to reply to this when you wrote, but then it disappeared from my notifications (because the issue was closed, I think).

Thanks for taking the time to report this, and indeed, it is pretty confusing. But as you mention, it's also not to do with colog, and just expected behaviour of the rust logging system.

In the meantime, I have published colog on crates.io, and I'd be happy to hear if you still use it, and if you find it useful?

**Comment by martinlindhe** [comment]
No longer using it, basically due to this issue i have resorted to using plain println!(), which is not very optimal but at least usable.

**Comment by chrivers** [comment]
Are you only using logging in tests, or does it just keep you from using it consistently?

I think it would be simple to detect when running under "cargo test", and perhaps do something better based on that. Would that have solved your particular problem?

**Comment by martinlindhe** [comment]
IIRC i was mainly using logging in error paths, and needed to see that output during testing, so I've been ignoring this since. I hope to learn of a better way eventually, but what i have works for now, thanks
