### ISSUE TITLE
If this had a way to set the current log level, then I'd switch to it

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [chrivers/rust-colog#2]
I'd like to parse a CL argument for the log level and filter out logs messages based on that, like my simple "simplog" logger does.... with that, I'd switch to it as I want colored output.

**Comment by chrivers** [comment]
Better late than never, right?

There's a `New And Improved (tm)` version of colog released just now, version `0.2.0`. If you look at `examples/levels.rs`, there's a demo of filtering based on the output level.

Please let me know if this solves your use case - in any case, I hope you'll give the new version a try.

**Comment by chrivers** [comment]
@andrewdavidmackenzie I haven't heard from you in a while, so I'll assume that this covers your use case. Thank you for the feedback.
